QDRANT_URL="https://226959fa-db16-4072-9033-bfb55f2114b7.us-west-1-0.aws.cloud.qdrant.io:6333"
QDRANT_API_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.GuXxpjwlPCEXNz0G0SrzUAa0mFuFP321AY35ug3kuFU"
